export const PERMISSIONS = {
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",

  CREATE_COMPANY: "CREATE_COMPANY",
  UPDATE_COMPANY: "UPDATE_COMPANY",
  DELETE_COMPANY: "DELETE_COMPANY",

  OCR_SCAN: "OCR_SCAN",

  VIEW_USERS: "VIEW_USERS",
  VIEW_COMPANIES: "VIEW_COMPANIES",
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS"
};