export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  MAIN_COMPANY_ADMIN: "MAIN_COMPANY_ADMIN",
  COMPANY_ADMIN: "COMPANY_ADMIN",
  STAFF: "STAFF",
  NORMAL_USER: "NORMAL_USER"
};

export default ROLES;
